version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      static-network:
        ipv4_address: 172.10.0.2
  web:
    build: './web'
    restart: always
    volumes:
      - ./web/www:/var/www/html
      - ./web/logs:/var/log/apache2
      - ./web/apache-conf:/etc/apache2
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      static-network:
        ipv4_address: 172.10.0.3
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
